# Stores MOGA constants
LENGTH_OF_BIT_STRING = 32
POPULATION_SIZE = 500
MUTATION_DISTRIBUTION_INDEX = 20  # Should be between 20-100
MUTATION_INDEX = 20
N = 2 #should be between 2-5
NUMBER_OF_ITERATIONS = 50
MUTATION_PROBABILITY = 0.1
NUMBER_OF_VARIABLES = 2
